### PR TITLE
Fixed integration.

### PR DESCRIPTION
**Pull request by bibonev**
So, it works guys 👍 
However, for every topic it gives me the same location. Probably that is some mocked data being passed through the server? If you have a spare minute, you can take a look at it.

### CODE REVIEW

**Comment by AkbarCS** [comment]
image

I get this error. Do you run it from templates/index or is there another way?

**Comment by simonnoff** [comment]
Try running the server python manage.py runserver 0.0.0.0:8000 and navigating to there!

**Comment by AkbarCS** [comment]
image

Tried installing webpack_loader, but that does not help either. Opening the index.html file still gives the same result as before.

**Comment by bibonev** [comment]
So, to run the application:
1. run 'npm install' in the static folder
2. run 'npm install webpack -g' in the static folder
3. run 'webpack --config webpack.local.config.js' from the static folder
4. pip install django-webpack-loader from the main folder
5. and then you can run python manage.py runserver 0.0.0.0:8000

*If any of them fails, leave it :)

**Pull request merged**
